// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: to_comment.proto

package frompublish

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ToCommentService service

func NewToCommentServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ToCommentService service

type ToCommentService interface {
	UpdateCommentCount(ctx context.Context, in *UpdateCommentCountRequest, opts ...client.CallOption) (*UpdateCommentCountResponse, error)
}

type toCommentService struct {
	c    client.Client
	name string
}

func NewToCommentService(name string, c client.Client) ToCommentService {
	return &toCommentService{
		c:    c,
		name: name,
	}
}

func (c *toCommentService) UpdateCommentCount(ctx context.Context, in *UpdateCommentCountRequest, opts ...client.CallOption) (*UpdateCommentCountResponse, error) {
	req := c.c.NewRequest(c.name, "ToCommentService.UpdateCommentCount", in)
	out := new(UpdateCommentCountResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ToCommentService service

type ToCommentServiceHandler interface {
	UpdateCommentCount(context.Context, *UpdateCommentCountRequest, *UpdateCommentCountResponse) error
}

func RegisterToCommentServiceHandler(s server.Server, hdlr ToCommentServiceHandler, opts ...server.HandlerOption) error {
	type toCommentService interface {
		UpdateCommentCount(ctx context.Context, in *UpdateCommentCountRequest, out *UpdateCommentCountResponse) error
	}
	type ToCommentService struct {
		toCommentService
	}
	h := &toCommentServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ToCommentService{h}, opts...))
}

type toCommentServiceHandler struct {
	ToCommentServiceHandler
}

func (h *toCommentServiceHandler) UpdateCommentCount(ctx context.Context, in *UpdateCommentCountRequest, out *UpdateCommentCountResponse) error {
	return h.ToCommentServiceHandler.UpdateCommentCount(ctx, in, out)
}
