// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: to_relation.proto

package from_message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ToRelationService service

func NewToRelationServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ToRelationService service

type ToRelationService interface {
	QueryMessagesByUsers(ctx context.Context, in *QueryMessagesByUsersRequest, opts ...client.CallOption) (*QueryMessagesByUsersResponse, error)
}

type toRelationService struct {
	c    client.Client
	name string
}

func NewToRelationService(name string, c client.Client) ToRelationService {
	return &toRelationService{
		c:    c,
		name: name,
	}
}

func (c *toRelationService) QueryMessagesByUsers(ctx context.Context, in *QueryMessagesByUsersRequest, opts ...client.CallOption) (*QueryMessagesByUsersResponse, error) {
	req := c.c.NewRequest(c.name, "ToRelationService.QueryMessagesByUsers", in)
	out := new(QueryMessagesByUsersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ToRelationService service

type ToRelationServiceHandler interface {
	QueryMessagesByUsers(context.Context, *QueryMessagesByUsersRequest, *QueryMessagesByUsersResponse) error
}

func RegisterToRelationServiceHandler(s server.Server, hdlr ToRelationServiceHandler, opts ...server.HandlerOption) error {
	type toRelationService interface {
		QueryMessagesByUsers(ctx context.Context, in *QueryMessagesByUsersRequest, out *QueryMessagesByUsersResponse) error
	}
	type ToRelationService struct {
		toRelationService
	}
	h := &toRelationServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ToRelationService{h}, opts...))
}

type toRelationServiceHandler struct {
	ToRelationServiceHandler
}

func (h *toRelationServiceHandler) QueryMessagesByUsers(ctx context.Context, in *QueryMessagesByUsersRequest, out *QueryMessagesByUsersResponse) error {
	return h.ToRelationServiceHandler.QueryMessagesByUsers(ctx, in, out)
}
