// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: to_publish.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ToPublishService service

func NewToPublishServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ToPublishService service

type ToPublishService interface {
	UpdateWorkCount(ctx context.Context, in *UpdateWorkCountRequest, opts ...client.CallOption) (*UpdateWorkCountResponse, error)
}

type toPublishService struct {
	c    client.Client
	name string
}

func NewToPublishService(name string, c client.Client) ToPublishService {
	return &toPublishService{
		c:    c,
		name: name,
	}
}

func (c *toPublishService) UpdateWorkCount(ctx context.Context, in *UpdateWorkCountRequest, opts ...client.CallOption) (*UpdateWorkCountResponse, error) {
	req := c.c.NewRequest(c.name, "ToPublishService.UpdateWorkCount", in)
	out := new(UpdateWorkCountResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ToPublishService service

type ToPublishServiceHandler interface {
	UpdateWorkCount(context.Context, *UpdateWorkCountRequest, *UpdateWorkCountResponse) error
}

func RegisterToPublishServiceHandler(s server.Server, hdlr ToPublishServiceHandler, opts ...server.HandlerOption) error {
	type toPublishService interface {
		UpdateWorkCount(ctx context.Context, in *UpdateWorkCountRequest, out *UpdateWorkCountResponse) error
	}
	type ToPublishService struct {
		toPublishService
	}
	h := &toPublishServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ToPublishService{h}, opts...))
}

type toPublishServiceHandler struct {
	ToPublishServiceHandler
}

func (h *toPublishServiceHandler) UpdateWorkCount(ctx context.Context, in *UpdateWorkCountRequest, out *UpdateWorkCountResponse) error {
	return h.ToPublishServiceHandler.UpdateWorkCount(ctx, in, out)
}
